# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SureCli < Formula
  desc "Agent-first CLI for Sure personal finance"
  homepage "https://github.com/we-promise/sure-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/we-promise/sure-cli/releases/download/v0.1.1/sure-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "5d8e903249f7f94e2e7c3814a17fc47e4734f1b7b85b2e27b983fd28de0f7105"

      def install
        bin.install "sure-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/we-promise/sure-cli/releases/download/v0.1.1/sure-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "784f43c52d09428cf47cc94c73892ec678aec94a7ce416a99af7e0a2c8672ac8"

      def install
        bin.install "sure-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/we-promise/sure-cli/releases/download/v0.1.1/sure-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "ef1cf3361bdf702d536c65aec2f76f583019aa50c5bae88369c010f0c97a3663"
      def install
        bin.install "sure-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/we-promise/sure-cli/releases/download/v0.1.1/sure-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "fdf4aa2d92429a6cd970daa1c980804cbfb74a422e3e76de077c4245b097f2b8"
      def install
        bin.install "sure-cli"
      end
    end
  end

  test do
    system "#{bin}/sure-cli", "--version"
  end
end
