# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SureCli < Formula
  desc "Agent-first CLI for Sure personal finance"
  homepage "https://github.com/we-promise/sure-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/we-promise/sure-cli/releases/download/v0.1.2/sure-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "f004806e66c3a014183e3e77d1d83d26b7cede6c333538650639b5997fc8e2c9"

      def install
        bin.install "sure-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/we-promise/sure-cli/releases/download/v0.1.2/sure-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "16d85900d32fd53edebfc5172f6d5c85e8729f65f823f9e85b328fd559353a24"

      def install
        bin.install "sure-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/we-promise/sure-cli/releases/download/v0.1.2/sure-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "42343f020a713919b886905a605a019b9e935c6d5ded65faf9852e31a1860b7b"
      def install
        bin.install "sure-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/we-promise/sure-cli/releases/download/v0.1.2/sure-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "79d605844502592fa552ffa3d7b3a0a23bbdc0f123804d3142c18edd4f442601"
      def install
        bin.install "sure-cli"
      end
    end
  end

  test do
    system "#{bin}/sure-cli", "--version"
  end
end
